#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend ageza.tech
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 416556-web-01 34.202.233.73:80 check
        server 416556-web-02 35.153.194.26:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start