#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Your script should only display:
#+ username
#+ muser id
#+ Home directory path for the use

while IFS= read -r LINE; do
    echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd
