#!/usr/bin/env bash

# Set the initial count to 0
count=0

# Loop while the count is less than 10
while [ $count -lt 10 ]
do

    # Print "Best School"
    echo "Best School"

    # Increment the count by 1
    (( count++ ))

done
