#!/usr/bin/env bash
# Display "Best School" 10 times.

counter=0
while [ $counter -lt 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    counter=$((counter + 1))
done
