#!/usr/bin/env bash
# Display "Best School" 10 times.

Iterator=0
while [ $Iterator -lt 10 ]
do
    if [ $Iterator = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    Iterator=$((Iterator + 1))
done
