#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" for the 4th counting
#   "good luck" for the 8th counting
#   "Best School" for all other counting

counter=0

while [ $counter -lt 10 ]
do
    if [ $counter -eq 3 ]
    then
        echo "bad luck"
    elif [ $counter -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
