#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
    # Display the current hour
    echo "Hour: $hour"

    minute=1
    while [ $minute -le 59 ]
    do
        # Display the current minute
        echo "$minute"

        # Increment the minute counter
        ((minute++))
    done

    # Increment the hour counter
    ((hour++))
done
