#!/usr/bin/env bash
# Creating a bash script that that uses ssh to connect
# to your server using the private key ~/.ssh/school
# with the user ubuntu.

# Server to connect to

ssh ubuntu@34.232.66.160 -i ~/.ssh/id_rsa
